### ISSUE TITLE
autoreconf AC_PROG_LIBTOOL warning

### ISSUE THREAD

**Issue by RobertCElliott** [fwts/fwts#12]
autoreconf -ivf results in:
```
autoreconf: running: /usr/bin/autoconf --force
configure.ac:9: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
configure.ac:9: You should run autoupdate.
```

That apparently changed in 2008 per https://www.gnu.org/software/libtool/manual/html_node/LT_005fINIT.html.

autoupdate suggests making this change to configure.ac:
```
-         AC_PROG_LIBTOOL
+         LT_INIT
```

**Comment by Ivanhu5866** [comment]
fix released on fwts version 24.09.00
