### ISSUE TITLE
Watchdog timer test should allow 0x00

### ISSUE THREAD

**Issue by superm1** [fwts/fwts#2]
On some platforms this failure comes up:
> Minimum Watchdog Reset Value is 0x00 and must be in the range 0x01..0xff

In this case the test does "strictly" match the spec because it doesn't reference 0x00.
![image](https://user-images.githubusercontent.com/494526/177837143-540bac30-d83a-4372-9f15-57d1fb419dec.png)

However 0x00 in this context means the watchdog timer is disabled.  So I don't believe FWTS should be failing this test.

**Comment by Ivanhu5866** [comment]
file a bug on lanchpad for tracking,
https://bugs.launchpad.net/fwts/+bug/1981429

**Comment by superm1** [comment]
Thanks!

**Comment by Ivanhu5866** [comment]
Released on fwts 22.07.00
