### ISSUE TITLE
acpi_table_check_fadt_p_lvl2_lat doesn't make sense on modern ACPI systems

### ISSUE THREAD

**Issue by superm1** [fwts/fwts#3]
On one of our systems we're observing the following medium error:
```
fadt: FADT P_LVL2_LAT is <= 100 (100) which implies a C2 state is supported but there is no P_BLK register block defined to enable the C2 transition.
```

Checking fwts code it seem this error comes if no `pblk` [could be detected](https://github.com/fwts/fwts/blob/d82204d836a6e6bf1ce491224923ea5072bed967/src/acpi/fadt/fadt.c#L1446)..  However looking how `pblk` is detected, it will only be detect when the system [has](https://github.com/fwts/fwts/blob/d82204d836a6e6bf1ce491224923ea5072bed967/src/acpi/fadt/fadt.c#L1428) `ACPI Type Processor`.

The comment there indicates that `_CST` may override it when declared as a `Device` object.  So shouldn't `_CST` be checked and waive this medium error too then?  

Looking at ACPI spec it actually [encourages the usage](https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/08_Processor_Configuration_and_Control/declaring-processors.html) of `Device` for processors.
> Processors are declared via the ASL Device statement. Declarations via the ASL Processor statement are deprecated

**Comment by superm1** [comment]
Forgot to mention - on this system it does use `Device` objects for processors.

```
    Scope (_SB)
    {
        Device (PLTF)
        {
            Name (_HID, "ACPI0010" /* Processor Container Device */)  // _HID: Hardware ID
            Name (_CID, EisaId ("PNP0A05") /* Generic Container Device */)  // _CID: Compatible ID
            Name (_UID, One)  // _UID: Unique ID
            Device (C000)
            {
                Name (_HID, "ACPI0007" /* Processor Device */)  // _HID: Hardware ID
                Name (_UID, Zero)  // _UID: Unique ID
            }
```

**Comment by Ivanhu5866** [comment]
Could you help to attach result.log and acpidump.log  for easier fixing and debugging by following the wiki, 
https://wiki.ubuntu.com/FirmwareTestSuite/FirmwareTestSuiteReportBug ? 
Thanks!

**Comment by Ivanhu5866** [comment]
Thanks!

The ACPI_DUMP.txt seems not the format that fwts needs,
```
Command: "fwts --dumpfile=ACPI_DUMP.txt fadt -".
Running tests: fadt.

fadt: FADT Fixed ACPI Description Table tests.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Cannot find FACP.
ACPI table FACP does not exist!
Aborted test, initialisation failed.
=======================================================================================================================================================================================================================================================
0 passed, 0 failed, 0 warning, 6 aborted, 0 skipped, 0 info only.
=======================================================================================================================================================================================================================================================


0 passed, 0 failed, 0 warning, 6 aborted, 0 skipped, 0 info only.

Test Failure Summary
=======================================================================================================================================================================================================================================================

Critical failures: NONE

High failures: NONE

Medium failures: NONE

Low failures: NONE

Other failures: NONE

Test           |Pass |Fail |Abort|Warn |Skip |Info |
---------------+-----+-----+-----+-----+-----+-----+
fadt           |     |     |    6|     |     |     |
---------------+-----+-----+-----+-----+-----+-----+
Total:         |    0|    0|    6|    0|    0|    0|
---------------+-----+-----+-----+-----+-----+-----+
```

And cannot be extracted by  acpica tool acpixtract
```
$ acpixtract -a ACPI_DUMP.txt 

Intel ACPI Component Architecture
ACPI Binary Table Extraction Utility version 20190509
Copyright (c) 2000 - 2019 Intel Corporation

Found non-printable char: 01 at file offset 1348248 (0x149298)
File appears to be binary (contains non-text or non-ascii characters)
```

Could you help to check it? and produce acpidump by 
```
$sudo acpidump > acpidump.log
or 
$sudo fwts --dump
```

**Comment by superm1** [comment]
Here is acpi dump.  This might not be the exact same BIOS that matches that results, it's a different system from same family but shows at least that same error.

[dump.log](https://github.com/fwts/fwts/files/9244852/dump.log)

**Comment by Ivanhu5866** [comment]
Thanks for the acpidump.
Create a launchpad bug for tracking.
https://bugs.launchpad.net/fwts/+bug/1983853

**Comment by Ivanhu5866** [comment]
patch sent to fwts-devel,
https://lists.ubuntu.com/archives/fwts-devel/2022-August/013541.html
