### ISSUE TITLE
`PWR_Button field in FACP should not be zero with ACPI PNP0C0C device` error doesn't make sense

### ISSUE THREAD

**Issue by superm1** [fwts/fwts#5]
In cross referencing to [ACPI spec](https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/05_ACPI_Software_Programming_Model/ACPI_Software_Programming_Model.html?highlight=PWR_BUTTON):

>A zero indicates the power button is handled as a fixed feature programming model; a one indicates the power button is handled as a control method device. If the system does not have a power button, this value would be “1” and no power button device would be present. Independent of the value of this field, the presence of a power button device in the namespace indicates to OSPM that the power button is handled as a control method device.

That is this there is no linkage that having a PNP0C0C device and that being zero is a problem.

**Comment by Ivanhu5866** [comment]
create a lanchpad bug for tracking, 
https://bugs.launchpad.net/fwts/+bug/2017737

**Comment by superm1** [comment]
Thanks for your support!
